Image_Manipulation_Api/Models/image.cs
namespace Image_Manipulation_Api.Models
{
    public class image
    {
        public int imglength { get; set; }

        public int imgwidth { get; set; }

        public string imgname { get; set; }

        public int blurpixalcount { get; set; }

        public int graypixalcount { get; set; }

        public string NormalImage { get; set; }

        public string WebPImage { get; set; }

    }
}

Image_Manipulation_Api/Controllers/WeatherForecastController.cs
using Microsoft.AspNetCore.Mvc;

namespace Image_Manipulation_Api.Controllers
{
    [ApiController]
    [Route("[controller]")]
    public class WeatherForecastController : Controller
    {
        private static readonly string[] Summaries = new[]
        {
        "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
    };

        private readonly ILogger<WeatherForecastController> _logger;

        public WeatherForecastController(ILogger<WeatherForecastController> logger)
        {
            _logger = logger;
        }

        [HttpGet(Name = "GetWeatherForecast")]
        public IEnumerable<WeatherForecast> Get()
        {
            return Enumerable.Range(1, 5).Select(index => new WeatherForecast
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = Random.Shared.Next(-20, 55),
                Summary = Summaries[Random.Shared.Next(Summaries.Length)]
            })
            .ToArray();
        }
    }
}

Image_Manipulation_Api/Controllers/imageController.cs
using Microsoft.AspNetCore.Mvc;
using Image_Manipulation_Api.Models;

namespace Image_Manipulation_Api.Controllers
{
    public class imageController : Controller
    {
        public object imglength { get; private set; }
        public object imgwidth { get; private set; }
        public object blurpixalcount { get; private set; }
        public object graypixalcount { get; private set; }

        public IActionResult Index()
        {
            return View();
        }
        [HttpPost]
        public ActionResult imgResize(image model)
        {
            if (ModelState.IsValid)
            {
                imgResize( imglength, imgwidth);
            }
            return View(model);
        }

        private void imgResize(object imglength, object imgwidth)
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        public ActionResult imgBlur(image model)
        {
            if (ModelState.IsValid)
            {
                imgBlur(blurpixalcount);
            }
            return View(model);
            
        }

        private void imgBlur(object blurpixalcount)
        {
            throw new NotImplementedException();
        }

        [HttpPost]
        public ActionResult imgGrayscale(image model)
        {
            if (ModelState.IsValid)
            {
                imgGrayscale(graypixalcount);
            }
            return View(model);
        }

        private void imgGrayscale(object graypixalcount)
        {
            throw new NotImplementedException();
        }

    }
}

Image_Manipulation_Api/Views/image/Index.cshtml
@model Image_Manipulation_Api.Models.image
@{
}
@{
}
<form id="form1" method="post" action="~/Controllers/">
    <div>
        <div>
            <FileUpload id="fileupload1"></FileUpload>

            <button id="button1" onclick="UploadFile(fileupload1)">Browse</button>

            <Image id="image1"></Image>

            @using (Html.BeginForm("imgResize", "image", FormMethod.Post))
            {
                @Html.TextBoxFor(model => model.imglength)
                @Html.TextBoxFor(model => model.imgwidth)
                <button type="submit">Crop</button>
            }
            @using (Html.BeginForm("imgBlur", "image", FormMethod.Post))
            {
                @Html.TextBoxFor(model => model.blurpixalcount)
                <button type="submit">Blur</button>
            }
            @using (Html.BeginForm("imgGrayscale", "image", FormMethod.Post))
            {
                @Html.TextBoxFor(model => model.graypixalcount)
                <button type="submit">GrayScale</button>
            }

        </div>

        <button type="submit" class="btn btn-firstimg" onclick="EditImg()">Apply</button>
    </div>

    <div>
        <div>
            <FileUpload id="fileupload2"></FileUpload>

            <button id="button2" onclick="UploadFile(fileupload2)">Browse</button>

            <Image id="image2"></Image>

            @using (Html.BeginForm("imgResize", "image", FormMethod.Post))
            {
                @Html.TextBoxFor(model => model.imglength)
                @Html.TextBoxFor(model => model.imgwidth)
                <button type="submit">Crop</button>
            }
            @using (Html.BeginForm("imgBlur", "image", FormMethod.Post))
            {
                @Html.TextBoxFor(model => model.blurpixalcount)
                <button type="submit">Blur</button>
            }
            @using (Html.BeginForm("imgGrayscale", "image", FormMethod.Post))
            {
                @Html.TextBoxFor(model => model.graypixalcount)
                <button type="submit">GrayScale</button>
            }

        </div>

        <button type="submit" class="btn btn-secondimg" onclick="EditImg()">Apply</button>
    </div>

    <div>
        <div>
            <FileUpload id="fileupload3"></FileUpload>

            <button id="button3" onclick="UploadFile(fileupload3)">Browse</button>

            <Image id="image3"></Image>

            @using (Html.BeginForm("imgResize", "image", FormMethod.Post))
            {
                @Html.TextBoxFor(model => model.imglength)
                @Html.TextBoxFor(model => model.imgwidth)
                <button type="submit">Crop</button>
            }
            @using (Html.BeginForm("imgBlur", "image", FormMethod.Post))
            {
                @Html.TextBoxFor(model => model.blurpixalcount)
                <button type="submit">Blur</button>
            }
            @using (Html.BeginForm("imgGrayscale", "image", FormMethod.Post))
            {
                @Html.TextBoxFor(model => model.graypixalcount)
                <button type="submit">GrayScale</button>
            }

        </div>

        <button type="submit" class="btn btn-thirdimg" onclick="EditImg()">Apply</button>
    </div>
    <button type="submit" class="btn btn-save">Save</button>
</form>